### ISSUE TITLE
Web API 2 - Cannot implicitly convert type 'Project.Models.ApplicationUser' to 'AccidentalFish.AspNet.Identity.Azure.TableUser'

### ISSUE THREAD

**Issue by davebro** [JamesRandall/AccidentalFish.AspNet.Identity.Azure#26]
I followed your "Web API 2" instructions exactly, and I'm getting an error after changing "IdentityUser" to "TableUser" in AccountController.cs in the "GetManageInfo" method. The error is: "Cannot implicitly convert type 'Project.Models.ApplicationUser' to 'AccidentalFish.AspNet.Identity.Azure.TableUser'". 

The line of code it's complaining about is: TableUser user = await UserManager.FindByIdAsync(User.Identity.GetUserId()); 

Any ideas? Thanks.

**Comment by JamesRandall** [comment]
Hi, did you get this fixed? Sorry for the delay - super busy week.

**Comment by davebro** [comment]
Hi, I did get it fixed, thank you! I opted to use your source files instead
of the ones generated by visual studio. I think there have been some
updates to identity since AccidentalFish was released. No worries though, I
replaced a lot of the generated code with the code from your solution, and
everything is working great. Thanks for the awesome work!

**Comment by JamesRandall** [comment]
Thanks for letting me know - this space has moved on a lot since I first wrote this code, I'll try and find time to revisit and update,
